import type { Metadata } from "next";
import { Figtree} from "next/font/google";
import "./globals.css";
import Sidebar from "../components/Sidebar";
import Player from "@/components/Player";

const font = Figtree({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TheBookHub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
      <Sidebar>

      {children}
        </Sidebar>
        <Player />
        </body>
    </html>
  );
}
